# Generated by Django 5.1 on 2024-08-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_id',
        ),
        migrations.RemoveField(
            model_name='call',
            name='host',
        ),
        migrations.AddField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='call',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='room_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='ringing', max_length=10),
        ),
    ]
